### PR TITLE
Allow formulas with variables of data frames

### PR DESCRIPTION
**Pull request by iago-pssjd**
My goal is to have the possibility of extend `frq(df, variables)` to `frq(df, formulas)`, as for example:
```
library(dplyr)
library(sjmisc)
frq(mtcars, cyl ==6)
iris %>% frq(Sepal.Length >5, starts_with("Petal"))
data(efc)
frq(efc,is.na(nur_pst), dplyr::contains("cop"))
```

### CODE REVIEW

**Comment by strengejacke** [comment]
Thanks, I'll take a closer look at this shortly. Can you give a short note when you're done working on this PR?

**Comment by iago-pssjd** [comment]
Sorry. I am already done on this PR. In fact, today I only made a minor modification (use `lapply` instead of a `for`) without further relevance.

Thanks.

**Comment by strengejacke** [comment]
I guess this PR should be merged before #111, right? Can you also add yourself as contributor to DESCRIPTION, if you don't mind being mentioned there?

**Comment by iago-pssjd** [comment]
I think both PR are independent and you can merge as you like. There should be no problem. In fact, I merged in the inverse order and it works.

I can add myself as contributor to DESCRIPTION. Is there some standard way to do it?

**Comment by strengejacke** [comment]
> Is there some standard way to do it?

I think this line:

```
person("Daniel", "Lüdecke", role = c("aut", "cre"), email = "d.luedecke@uke.de", comment = c(ORCID = "0000-0002-8895-3206"))
```

must be expanded to, adding your information into `c(...)`:

```
person(
  c("Daniel", "Lüdecke", role = c("aut", "cre"), email = "d.luedecke@uke.de", comment = c(ORCID = "0000-0002-8895-3206")),
  c(...)
)
```

you need to provide the role (`"ctb"` I would suggest), and optionally email/orcid.

**Comment by strengejacke** [comment]
Ok, actually it looks like this:

```
Authors@R: c(
	person("Dominique", 
		"Makowski", 
		email = "dom.makowski@gmail.com",
		role = c("aut", "cre"), 
		comment = c(ORCID = "0000-0001-5375-9967")),
	person("Daniel", 
		"Lüdecke", 
		role = c("aut"), 
		email = "d.luedecke@uke.de", 
		comment = c(ORCID = "0000-0002-8895-3206"))
	)
```

**Comment by iago-pssjd** [comment]
Done

**Comment by strengejacke** [comment]
Thanks!

**Comment by iago-pssjd** [comment]
Thanks to you!

**Comment by iago-pssjd** [comment]
One comment more. I saw you specified that the new expressions `frq` can compute after this PR are logical conditions. So are the examples I wrote. But today I thought in that, and in fact you can compute the frequencies of other operations, as 
```
mtcars %>% frq((gear + carb)/cyl)
```
I should have thought in other kind of examples. You may get one better than previous one.
Sorry for lack of detail. Thanks again.

**Comment by strengejacke** [comment]
That's cool! I'll look into it and add that to the docs

**Pull request merged**
